package com.example.entity;

// Generated 13 Sep, 2017 5:11:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * OauthCodeId generated by hbm2java
 */
@Entity
public class OauthCodeId implements java.io.Serializable {
	@Id
	private String code;
	private byte[] authentication;

	public OauthCodeId() {
	}

	public OauthCodeId(String code, byte[] authentication) {
		this.code = code;
		this.authentication = authentication;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "authentication")
	public byte[] getAuthentication() {
		return this.authentication;
	}

	public void setAuthentication(byte[] authentication) {
		this.authentication = authentication;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OauthCodeId))
			return false;
		OauthCodeId castOther = (OauthCodeId) other;

		return ((this.getCode() == castOther.getCode()) || (this.getCode() != null
				&& castOther.getCode() != null && this.getCode().equals(
				castOther.getCode())))
				&& ((this.getAuthentication() == castOther.getAuthentication()) || (this
						.getAuthentication() != null
						&& castOther.getAuthentication() != null && Arrays
							.equals(this.getAuthentication(),
									castOther.getAuthentication())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37
				* result
				+ (getAuthentication() == null ? 0 : Arrays.hashCode(this
						.getAuthentication()));
		return result;
	}

}
